stages:
  - validate
  - update

validate_workflows_dev:
  stage: validate
  image: gitlab-registry.cern.ch/cloud/ciadm
  script:
    - OS_CLOUD=tstack scripts/validate.sh

validate_workflows_prod:
  stage: validate
  image: gitlab-registry.cern.ch/cloud/ciadm
  script:
    - OS_CLOUD=cern scripts/validate.sh

update_workflows_dev:
  stage: update
  image: gitlab-registry.cern.ch/cloud/ciadm
  only:
    - master
  script:
    - OS_CLOUD=tstack scripts/update.sh

update_workflows_prod:
  stage: update
  image: gitlab-registry.cern.ch/cloud/ciadm
  only:
    - master
  script:
    - OS_CLOUD=cern scripts/update.sh
