stages:
  - validate
  - update

validate_dev:
  stage: validate
  image: gitlab-registry.cern.ch/cloud/ciadm
  script:
    - export OS_CLOUD=tstack
    - bash scripts/validate.sh

validate_prod:
  stage: validate
  image: gitlab-registry.cern.ch/cloud/ciadm
  script:
    - export OS_CLOUD=cern
    - bash scripts/validate.sh

update_dev:
  stage: update
  image: gitlab-registry.cern.ch/cloud/ciadm
  only:
    - master
  script:
    - export OS_CLOUD=tstack
    - bash scripts/update.sh

update_prod:
  stage: update
  image: gitlab-registry.cern.ch/cloud/ciadm
  only:
    - master
  script:
    - export OS_CLOUD=cern
    - bash scripts/update.sh
